### ISSUE TITLE
docker image is error

### ISSUE THREAD

**Issue by huayanqiaq** [DrewThomasson/ebook2audiobookXTTS#16]
have this error

starting...
Device selected is: cuda
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Running on local URL:  http://127.0.0.1:7860

Could not create share link. Missing file: /opt/conda/envs/ebookenv/lib/python3.10/site-packages/gradio/frpc_linux_amd64_v0.2.

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps:

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /opt/conda/envs/ebookenv/lib/python3.10/site-packages/gradio

i feel your docker image hub have been hacked
because you use frp software
This is an intranet penetration software
It's also the malware that's being utilized by all the hackers.

**Comment by DrewThomasson** [comment]
lol, NO.

I don't think its anything related to hackers, 

Thats just an issue with running gradio on ARM computers, 

I only get that issue on my ARM devices but not my x86 devices.

I'll just fix it by making the docker image work with the local url,

 thus making the public url not even needed at all

**Comment by DrewThomasson** [comment]
Fixed lol

The new docker commands are:


#### 🚀 Running the Docker Container

To run the Docker container and start the Gradio interface, use the following command:

 -Run with CPU only
```powershell
docker run -it --rm -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py
```
 -Run with GPU Speedup (Nvida graphics cards only)
```powershell
docker run -it --rm --gpus all -p 7860:7860 --platform=linux/amd64 athomasson2/ebook2audiobookxtts:huggingface python app.py
```

Now that they will run entirely locally this issue should not show up anymore
