### ISSUE TITLE
The output m4b doesn't work

### ISSUE THREAD

**Issue by nitinmukesh** [DrewThomasson/ebook2audiobookXTTS#21]
So, I run the program using docker and used webUI to convert small 2 page PDF

![image](https://github.com/user-attachments/assets/cb4f65c4-7a34-437e-bfbb-1a0d5bb76134)

It showed conversion is complete. I downloaded the file using the download icon at the top-right of Audiobook Player.

Now I tried playing using VLC, also tried converting using online convertors. Nothing is working.

How to use this file. (attached the output as zip)
[comic.zip](https://github.com/user-attachments/files/17316913/comic.zip)

Log
<details>
Output #0, ipod, to './Audiobooks/comic.m4b':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 7350 Hz, mono, fltp, 44 kb/s
    Metadata:
      encoder         : Lavc59.37.100 aac
  Stream #0:1: Video: png, rgb24(pc, gbr/unknown/unknown, progressive), 1275x1650 [SAR 1:1 DAR 17:22], q=2-31, 200 kb/s, 25 fps, 12800 tbn (attached pic)
    Metadata:
      encoder         : Lavc59.37.100 png
frame=    1 fps=0.0 q=-0.0 Lsize=    1517kB time=00:00:00.00 bitrate=159274051.3kbits/s speed=0.000509x
video:1516kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.018163%
[aac @ 0x5592a7cc5880] Qavg: nan
Audiobook created at ./Audiobooks/comic.m4b
</details>

**Comment by DrewThomasson** [comment]
It's probs because your input pdf has no text in it, considering it's a pdf of a comic book.

Your comic pdf is most likely a set of images of pages of the comic book.

So when it converts it you get a txt file that contains no text.

**Comment by nitinmukesh** [comment]
Oh ok. Got it.

**Comment by DrewThomasson** [comment]
Here's a huggingface space that'll to the PDF OCR to TXT step for you tho lol.

https://huggingface.co/spaces/drewThomasson/PDF-to-TXT-OCR?logs=build
