### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [DrewThomasson/ebook2audiobookXTTS#24]
It would be nice to be able to install the git repo directly with "pip install -e .", but no reuirements.txt etc...

**Comment by DrewThomasson** [comment]
Tru.

If you make a merge request with that added to the repo I'll merge it lol

Then you'll be able to have your name under the list of `Contributors` on the main page of the repo

**Comment by ROBERT-MCDOWELL** [comment]
I need to know all components needed and their versions, and python version too.

**Comment by ROBERT-MCDOWELL** [comment]
for the setup.py, it needs a main function but in app.py there is not, and depends on the args headless or not which is not manageable for the setup.py. maybe envelp it with a __main__ should be ok.

**Comment by ROBERT-MCDOWELL** [comment]
yeah it needs also a main function into app.py. or more logical merge app.py into ebook2audiobook.py so I can use the "main" function as an entry point

**Comment by ROBERT-MCDOWELL** [comment]
PR done!
