### ISSUE TITLE
XTTS Hallucinations

### ISSUE THREAD

**Issue by DrewThomasson** [DrewThomasson/ebook2audiobookXTTS#34]
I tried your fix of changing the temperature. As you said, it did improve hallucinations, but did not seem to fix the issue entirely. 
From my testing, hallucinations seem to appear when a paragraph ends on a quotation mark. The model almost always hallucinates when a paragraph ends with ?" or !" (so a 'spoken' question or exclamation with an ending quote.). Paragraphs not ending on a quote (almost?) never seem to cause hallucinations, while paragraphs ending on ." sometimes cause them.

In your 'mini_story - Drew.epub' for example, it will 100% hallucinate for me at the sentence '“Moths? My dear, these silks could turn away the sharpest of blades!”', no matter what sampler settings I try.

All my testing was done using ebook2audiobookxtts.

I am unsure if this is an inherent limitation of XTTS, but if this could somehow be fixed, this would make an already great project absolutely fantastic imo, since XTTS seems to be the by far most natural sounding TTS model for audiobook narration.

_Originally posted by @sotir3d in https://github.com/DrewThomasson/VoxNovel/discussions/36#discussioncomment-10987088_

**Comment by sotir3d** [comment]
posting here again.

I tried both. 0.1 was actually horrible for me, but I only tried one gen with it. 1 came out almost perfect though, apart from the stuff I mentioned (a 4 hour gen with around 40k words.)

Not sure if this is the same case with TTS models since I'm really not that well versed with them, but for LLMs a temp of 1 usually means default.

**Comment by DrewThomasson** [comment]
thx thx @sotir3d 

Well according to the [coqui tts docs here ](https://docs.coqui.ai/en/latest/models/xtts.html#inference-parameters)

## `temperature` : The softmax temperature of the autoregressive model. Defaults to 0.65.

but interesting to find that its working fine for you at 1

usually it becomes incomprehensible for me at 1 lol

I suppose one extra thing you could try doing is cleaning up the speaker audio sample your suing to clone a voice

Here's a huggingface I made that'll remove all background sounds and such prioritizing only the person talking

https://huggingface.co/spaces/drewThomasson/DeepFilterNet2_no_limit?logs=container

**Comment by sotir3d** [comment]
I was actually using the default, without any target voice or custom model. Just the epub and temp to 1. Maybe that's why it doesn't go too crazy at 1?

**Comment by DrewThomasson** [comment]
lol

The model "technically" has no default voice

In order to function XTTS needs a voice sample

I just made the model point to a default voice sample I put in the repo lol
[default_voice.wav](https://github.com/DrewThomasson/ebook2audiobookXTTS/blob/main/default_voice.wav)

**Comment by sotir3d** [comment]
Ah ok makes sense. It's actually a pretty good narration voice though lol

**Comment by DrewThomasson** [comment]
lol thx I tried my best to give it a good default, 😎

I might look into adding the ability for the model to generate multiple versions of every xtts audio generation and then have it select the best one 🤔

But I'm still putting that on hold as it would increase the inference Time by like 3FOLD 😔

Just isn't worth it lol

## Anyway with that I guess I'll be closing this issue as its been solved

- Reopen it if you run into any other issues lol
