### ISSUE TITLE
 numpy 2.0.0 breakage

### ISSUE THREAD

**Issue by Rihcus** [DrewThomasson/ebook2audiobookXTTS#5]
Recently  numpy 2.0.0 was released and it seams to break a part of torch.

```
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in <module>
    device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),
/opt/conda/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
```

Downgrading to version 1.26.4 seems to fix issue for now

`pip install numpy==1.26.4`

**Comment by DrewThomasson** [comment]
Oh shoot thx for letting me know!

I'll get on modifying the install txt files to have that edit 

👍⭐️

**Comment by DrewThomasson** [comment]
Which install method did you use also?

**Comment by Rihcus** [comment]
`Which install method did you use also?`

The ubuntu one?

I'm actually using this script on kaggle similar to colab


```
#!DEBIAN_FRONTEND=noninteractive
!sudo apt-get update # && sudo apt-get -y upgrade
!sudo apt-get -y install libegl1 
!sudo apt-get -y install libopengl0
!sudo apt-get -y install libxcb-cursor0
!sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
!sudo apt-get install -y ffmpeg
!pip install tts pydub nltk beautifulsoup4 ebooklib tqdm
!pip install numpy==1.26.4
```

root@571ce3117db5 
----------------- 
OS: Ubuntu 20.04.6 LTS x86_64 
Host: Google Compute Engine 
Kernel: 5.15.133+ 
Uptime: 46 mins 
Packages: 725 (dpkg) 
Shell: bash 5.0.17 
Terminal: jupyter-noteboo 
CPU: Intel Xeon (4) @ 2.000GHz 
GPU: NVIDIA Tesla T4 
GPU: NVIDIA Tesla T4 
Memory: 844MiB / 32110MiB

**Comment by DrewThomasson** [comment]
Sorry about the late response I'll see if you modification breaks the colab or not later,

If it does then I'll make a separate ipyb file for kaggel,


Or easier If you send the kaggel script your using to run it I'll just put that in the repo and readme on kaggel running info lol

**Comment by Rihcus** [comment]
> Sorry about the late response I'll see if your modification breaks the colab or not later,
> 
> If it does then I'll make a separate ipyb file for kaggel,
> 
> Or easier If you send the kaggel script your using to run it I'll just put that in the repo and readme on kaggel running info lol

Here is the kaggle notebook (its not the most elegant thing).

https://github.com/Rihcus/ebook2audiobookXTTS/blob/main/kaggle-ebook2audiobook-demo.ipynb

I have made some changes to the code (In a attempt to enable multi gpu support)
https://github.com/Rihcus/ebook2audiobookXTTS

**Comment by DrewThomasson** [comment]
## AAAAA I remembered about this I'm SO SORRY 😭

## Your kaggle requirements install still works amazingly with the current updated implementation of ebook2audiobookxtts +WEB GUI!!! 🎉

- If you make your kaggel version GitHub repo up to date with mine so its mergable
- and make it so that it works with everything in the current state
- and put the new kaggle files if you can in a new folder in the repo named `/Notebooks`

### Please update, Then I will gladly merge your pull request! 🎉 😭

- I'd love to get your name under the `Contributor list` on my repo 😭


## Also:


Dude I don't know how you fixed the issues with getting Coqio xtts working in Google Colab or kaggel but like, it freakin works lol. 

I Might try using your fix thing to get my xtts fine tuning Google Colab updated and working later as well 🎉 😭

**Comment by DrewThomasson** [comment]
Re-opening this so I make sure not to forget before I get a response/update on this 😭

**Comment by DrewThomasson** [comment]
### Link to Google Colab Notebook I Used to test your Kaggel script on

[Google Colab Notebook](https://colab.research.google.com/drive/1JhPFPnYs9JVuSRA9yLhHsbHFR3aNs5qg?usp=sharing)

**Comment by DrewThomasson** [comment]
Well my Google Colab just launches the gradio web interface with a public link

So all the stuff like giving it the ebook should work in the gradio interface

**Comment by Rihcus** [comment]
I synced the repo and added the Notebooks folder.

For colab made a small tweak:

1. Added gradio dependency (colab was complaining it wasn't installed for me)

`!pip install gradio`

2. Imported ntlk (not sure if its needed got an error without it) set xtts to auto accept (avoids having to type y to download xtts).

```
#ntlk error fix
#https://github.com/delip/PyTorchNLPBook/issues/14
import nltk
nltk.download('punkt')

#Auto agree to xtts
import os
os.environ["COQUI_TOS_AGREED"] = "1"
```

I have also added a kaggle version however kaggle is been acting very buggy.

When installing dependencies kaggles note book UI crashes for me in both chrome and firefox:

![SCR-20241011-ilst](https://github.com/user-attachments/assets/c5be5a2a-c5f6-434d-b105-c0b24ccf4fd5)

When I run the app.py cell kaggle starts up gratio then weirdly kills the program and shuts down the notebook (mentioning keyboard interrupt) currently not sure why :(

```
Running on local URL: http://172.19.2.2:7860
Running on local URL: http://localhost:7860
* Running on local URL:  http://0.0.0.0:7860
* Running on public URL: https://759c5f2bfe0dfd8e61.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
^C
Keyboard interruption in main thread... closing server.
Killing tunnel 0.0.0.0:7860 <> https://759c5f2bfe0dfd8e61.gradio.live
Kernel title updated to Kaggle BETA of ebook2audiobookxtts.ipynb
```

**Comment by DrewThomasson** [comment]
Seems it's Kaggel preventing tunneling is why for the public link:

"Many forms of tunneling are automatically banned to prevent misuse, including frp, I'll see if we can ease this for gradio."

People talking about the issue your seeing:
https://www.kaggle.com/discussions/product-feedback/377918

**Comment by DrewThomasson** [comment]
I'll be closing this for now cause At least the Google Colab works lol,

At least headless mode seems to work on your Kaggle side 👍🎉
