### ISSUE TITLE
Calibre is not installed. Please install Calibre for this functionality.

### ISSUE THREAD

**Issue by FuxorLuck** [DrewThomasson/ebook2audiobookXTTS#6]
I get this error
when I try to install it via power shell via the command "choco install calibre"
I get the error choco isnt recognized function

Thanks

**Comment by DrewThomasson** [comment]
You have to install chocho manually it is not built into windows. 

https://chocolatey.org/install#individual

**Comment by DrewThomasson** [comment]
You may have to install calibre manually with this also

https://calibre-ebook.com/download_windows

**Comment by DrewThomasson** [comment]
Installing docker and just running the docker command might be easier tho
That'll give you a web interface,

**Comment by FuxorLuck** [comment]
> Installing docker and just running the docker command might be easier tho That'll give you a web interface,

I installed it and It's over 23GB 
My pc also became much slower
I give up

Thank you anyway

**Comment by DrewThomasson** [comment]
You can delete the docker image at least is the whole point of it 

Sorry to hear about your issues

Docker images do tend to run slower than running it natively as it usually uses virtualization

**Comment by DrewThomasson** [comment]
You could try uninstalling docker and running 

'wsl --shutdown'

That should fix your slow computer issue

**Comment by FuxorLuck** [comment]
I installed Calibare again and this time i get an error
An error occurred while converting the eBook: Command '['ebook-convert', 'python', '.\\Working_files\\temp.epub']' returned non-zero exit status 1.

**Comment by DrewThomasson** [comment]
Did you try installing calibre from their site instead of through Choco?

**Comment by FuxorLuck** [comment]
site

**Comment by DrewThomasson** [comment]
Weird I'll look into this tomorrow

**Comment by FuxorLuck** [comment]
Fixed it, just drag and drop the file instead of writing a command

**Comment by DrewThomasson** [comment]
Interesting, I didn't know my app had drag and drop functionality

**Comment by FuxorLuck** [comment]
![image](https://github.com/user-attachments/assets/8b2cb3c2-22ff-42db-ae67-adc6dbfe345c)

new error

**Comment by DrewThomasson** [comment]
How are you launching the program what command

**Comment by FuxorLuck** [comment]
just drag the ebook and drop it into the script

**Comment by DrewThomasson** [comment]
Idk try manually selecting the reference audio wav file

**Comment by FuxorLuck** [comment]
no audio file is being created

**Comment by DrewThomasson** [comment]
Into the script, ok what command did you use to launch the python program?

**Comment by FuxorLuck** [comment]
"D:\My Edits\Golgotha\ebook2audiobook.py" python ebook2audiobook.py <path_to_ebook_file>

**Comment by DrewThomasson** [comment]
Pretty sure you have to use it like this or things get messed up

This exact structure 

'python ebook2audiobook.py <path_to_ebook_file> [path_to_voice_file] [language_code]'


Also so you modified the script?

Idk is there a file called default_voice.wav in the same folder as the python script your running 

That has to be there

**Comment by FuxorLuck** [comment]
I didn't modify the script
if I do it your way I get a message that ebook2audiobook.py isn't found

Listen your program convert the ebook to text
Is there any way to use TTS Coqui to convert the text to mp3?

**Comment by FuxorLuck** [comment]
nevermind i fixed it, it couldnt locate the voice file

**Comment by DrewThomasson** [comment]
Yeah sorry that's what I was asking, coqui xtts needs a example voice audio file to work, that's why included that wav file in the GitHub repo as the default

**Comment by FuxorLuck** [comment]
Thank you
once it will finish I will close the issue

**Comment by DrewThomasson** [comment]
Kk

**Comment by DrewThomasson** [comment]
Hope you have an nvidia gpu

This program runs very very very slow on cpu only

**Comment by FuxorLuck** [comment]
> Hope you have an nvidia gpu
> 
> This program runs very very very slow on cpu only

I have NVIDIA GPU (GTX 1060 6GB) 
It did 500 sentences in 2 hours

am I running the program on cpu or gpu mod? If cpu, how do I change to gpu?

**Comment by DrewThomasson** [comment]
Your probs fine then

**Comment by FuxorLuck** [comment]
Is there any option to pause the process shut down the pc and day later to continue from the same place?

**Comment by DrewThomasson** [comment]
It resets everytime you run it

So it's more of a just run overnight program if anything,

High quality tts takes time on consumer hardware sadly

**Comment by FuxorLuck** [comment]
well it works thank you very much

**Comment by DrewThomasson** [comment]
👍

Your probably going to get around real time speaking speed tts generation on your graphics card

So to generate a 2 hour audiobook might take 2-4 hours for your computer

**Comment by FuxorLuck** [comment]
> 👍
> 
> Your probably going to get around real time speaking speed tts generation on your graphics card
> 
> So to generate a 2 hour audiobook might take 2-4 hours for your computer

I just opened task manager and it tells me that I use CPU and not gpu

**Comment by FuxorLuck** [comment]
> It resets everytime you run it
> 
> So it's more of a just run overnight program if anything,
> 
> High quality tts takes time on consumer hardware sadly

You can just delete the text file of the chapters the program already did (from temp_ebook) just do it after the program reextracted the files, and it will continue from the moment it stops
