### ISSUE TITLE
Program is runing on CPU and not GPU

### ISSUE THREAD

**Issue by FuxorLuck** [DrewThomasson/ebook2audiobookXTTS#7]
I have GTX 1060 6gb
When I open the task manager it tells me that the prigram is using my cpu not gpu
How can I fix that ?

**Comment by DrewThomasson** [comment]
What OS are you running it on,

And how are you running it, like docker or a specific python file?

**Comment by FuxorLuck** [comment]
windows
python 3.11

**Comment by DrewThomasson** [comment]
Natively on windows or through wsl

**Comment by FuxorLuck** [comment]
Natively on windows

**Comment by DrewThomasson** [comment]
Run 


python -c "import torch; print(torch.cuda.is_available())"



That'll tell you True or false if you have cuda available on your system

**Comment by FuxorLuck** [comment]
False

but gtx 1060 has CUDA cores
source: https://www.nvidia.com/en-us/geforce/news/gfecnt/nvidia-geforce-gtx-1060/

**Comment by DrewThomasson** [comment]
Check if the cuda toolkit is installed on your system with this

nvcc --version

**Comment by FuxorLuck** [comment]
'nvcc' is not recognized as an internal or external command,
operable program or batch file.

how do i install cuda toolkit

**Comment by DrewThomasson** [comment]
https://developer.nvidia.com/cuda-downloads



Unsure I've never seen a windows computer run into this before, 


You could also try updating your nvidia drivers and restarting before this just in case it's that

**Comment by FuxorLuck** [comment]
> https://developer.nvidia.com/cuda-downloads
> 
> Unsure I've never seen a windows computer run into this before,
> 
> You could also try updating your nvidia drivers and restarting before this just in case it's that

I installed it 
I do get the message 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Nov_11_20:26:34_PST_2024
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.3188296_0

but for python -c "import torch; print(torch.cuda.is_available())"
it says false

**Comment by DrewThomasson** [comment]
Did you restart your computer?

**Comment by FuxorLuck** [comment]
yes

**Comment by DrewThomasson** [comment]
Did you update your nvidia driver?

**Comment by FuxorLuck** [comment]
I will try

**Comment by FuxorLuck** [comment]
I checked now and I am on the latest version

**Comment by DrewThomasson** [comment]
Version

560.81  WHQL?



 idk

https://www.nvidia.com/download/driverResults.aspx/230594/en-us/

**Comment by DrewThomasson** [comment]
Another possibility is that you should be using python 3.10 instead of python 3.11, 


only recently did they add support for cuda in 3.11 so there might be issues,

**Comment by FuxorLuck** [comment]
I am using python 3.11 
I will try o reinstall the driver

**Comment by DrewThomasson** [comment]
👍

So if that doesn't work then all I know left is

# (1.)
(As before) downgrade to 3.10 (which is the most stable and widely supported version) which I could help you with uninstalling the pips and such if needed


# (2.)
Just run the docker version of it and see if that works,

### Pros:

- being able to launch/download/install with a single command

-if storage is an issue then you can just delete the docker image easy peasy no mess.

### cons:

- might run slower than natively GPU at only half GPU speed but would still be faster than native with only cpu speed

-sometimes docker on windows is - smig annoying the first setup:

**Comment by FuxorLuck** [comment]
Thanks

**Comment by DrewThomasson** [comment]
You'll never believe it, I'm getting the same error on my windows computer now

**Comment by DrewThomasson** [comment]
## FIXED ON MY END WILL UPDATE HOW

**Comment by DrewThomasson** [comment]
1) updated my nvidia drivers

2) installed mini conda to make it easier 

3) created a python 3.10 env in mini conda to use and activate everything I do will be in this 3.10 env

4) uninstall cuda (can be done in the uninstall apps in windows)

5) Install Cuda 11.8

6) install torch for cuda 11.8 


7) ran test commands and now gpu is detected

**Comment by FuxorLuck** [comment]
I got True thank you very much

**Comment by DrewThomasson** [comment]
# YES!!!! 🎉

**Comment by abiroid** [comment]
Try adding --gpus=all to your docker command
Example:
docker run -it --rm --gpus=all -p 7860:7860 athomasson2/ebook2audiobookxtts:latest

I'm running it on Windows 11 and got same error. But works with this option.

**Comment by DrewThomasson** [comment]
> Try adding --gpus=all to your docker command
> 
> Example:
> 
> docker run -it --rm --gpus=all -p 7860:7860 athomasson2/ebook2audiobookxtts:latest
> 
> 
> 
> I'm running it on Windows 11 and got same error. But works with this option.

## That is true, 

-Only downside is as far as I can tell docker seems to run at around half the speed of natively running on windows.

-So natively getting CUDA working on windows seems to be annoying but you do get more of a speed up.



### Granted 

- docker is WAYYYY EASIER, I ALWAYS recommend it.

#### ❗️ALSO you mentioning this made me realize that the GPU docker command wasn't on the github readme!

- Thank you for bringing this to my attention,

-I'll update the readme with this information added to it.

**Comment by Code4SAFrankie** [comment]
How do I access the locally installed program's miniconda in order to install the proper gpu torch?

**Comment by ROBERT-MCDOWELL** [comment]
cd /path/to/ebook2audiobook 
conda activate .\python_env  (windows)
conda activate ./python_env (linux/mac)
